name: Build APK
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Build with Buildozer
      uses: ArtemSBulgakov/buildozer-action@v1
      with:
        command: buildozer android debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: auto-lock-timer-pro-apk
        path: bin/*.apk
